### ISSUE TITLE
Contents of top app bar are not vertically centered on home screen

### ISSUE THREAD

**Issue by mddanishansari** [akshay2211/Paper#12]
Normal screenshot
![Screenshot_2021-12-16-20-33-58-539_io ak1 paper](https://user-images.githubusercontent.com/11080523/146396846-ea637784-ebb8-4d95-97d0-03f4d50eb48d.jpg)

Layout bounds enabled screenshot
![Screenshot_2021-12-16-20-36-46-460_io ak1 paper](https://user-images.githubusercontent.com/11080523/146396840-078795e9-e7b1-45dd-9334-e6539203ae4d.jpg)

**Comment by mddanishansari** [comment]
@akshay2211 mind if I open PR to fix this or do you already know about it?

**Comment by akshay2211** [comment]
@mddanishansari thanks for trying paper
Contribution from your side would be appreciated.
