### ISSUE TITLE
The settings screen extends to the NavigationBar at the bottom.

### ISSUE THREAD

**Issue by tenSunFree** [akshay2211/Paper#59]
The settings screen extends to the NavigationBar at the bottom, which will lead to a poor user experience.
![Screenshot_20220530-002409](https://user-images.githubusercontent.com/23090085/170880881-fd977696-a369-47f3-8e8d-1e3b7e065e5a.png)

Maybe consider adding navigationBarsPadding.
![2022-05-30_002456](https://user-images.githubusercontent.com/23090085/170880894-9d5c0382-691b-4cbd-bbf1-1d58aed30631.jpg)
![Screenshot_20220530-002600](https://user-images.githubusercontent.com/23090085/170880901-b96aac45-8ded-4023-8df7-97c918657d0f.png)

**Comment by akshay2211** [comment]
Thankyou @tenSunFree, for pointing out this issue in [Paper](https://github.com/akshay2211/Paper)
I'll surely resolve it in few days.
