### ISSUE TITLE
What to do about : rootProject.file("../keys/paper.properties")

### ISSUE THREAD

**Issue by nadirspam** [akshay2211/Paper#84]
When building the project I got this error from gradle:

/home/../keys/paper.properties (No such file or directory)

I tried to create an empty paper.properties file but I got an error about path=null

**Comment by akshay2211** [comment]
Hello @nadirspam,
you don't need release-config to run the app
kindly comment the [signingConfigs](https://github.com/akshay2211/Paper/blob/8249971088fb50df5a461a4f99e8a884b3b5b13f/app/build.gradle#L32) and its use on line number  [51](https://github.com/akshay2211/Paper/blob/8249971088fb50df5a461a4f99e8a884b3b5b13f/app/build.gradle#L51)
